### ISSUE TITLE
PlayerHandshake/Login/DisconnectCallbacks?

### ISSUE THREAD

**Issue by i509VCB** [FabLabsMC/networking-api-v1-draft#2]
This seems like the right place to do those kinds of callbacks.

You would probably want a client and server specific variant of the callbacks.

**Comment by liach** [comment]
I currently have server:
play initialized (player joined and can send packet)
https://github.com/FabLabsMC/networking-api-v1-draft/blob/10d1c03d0439cbc93026327a7befc207c329bd7b/src/main/java/io/github/fablabsmc/fablabs/api/networking/v1/server/ServerNetworking.java#L91
login query start
https://github.com/FabLabsMC/networking-api-v1-draft/blob/10d1c03d0439cbc93026327a7befc207c329bd7b/src/main/java/io/github/fablabsmc/fablabs/api/networking/v1/server/ServerNetworking.java#L114
play disconnection
https://github.com/FabLabsMC/networking-api-v1-draft/blob/10d1c03d0439cbc93026327a7befc207c329bd7b/src/main/java/io/github/fablabsmc/fablabs/api/networking/v1/server/ServerNetworking.java#L102
login disconnection
https://github.com/FabLabsMC/networking-api-v1-draft/blob/10d1c03d0439cbc93026327a7befc207c329bd7b/src/main/java/io/github/fablabsmc/fablabs/api/networking/v1/server/ServerNetworking.java#L125




For client:
play initialized (player joined and can send packet)
https://github.com/FabLabsMC/networking-api-v1-draft/blob/10d1c03d0439cbc93026327a7befc207c329bd7b/src/main/java/io/github/fablabsmc/fablabs/api/networking/v1/client/ClientNetworking.java#L65
play disconnected
https://github.com/FabLabsMC/networking-api-v1-draft/blob/10d1c03d0439cbc93026327a7befc207c329bd7b/src/main/java/io/github/fablabsmc/fablabs/api/networking/v1/client/ClientNetworking.java#L76

No login versions for client as clients are passive for login; can only respond to query, cannot send query actively. Dunno if there's a need for client login disconnection at all

**Comment by liach** [comment]
Looking at @ramidzkh's question on discord, he should use `ClientNetworking.PLAY_INITIALIZED` for his sending packet to server on login purpose. So this problem is not valid as I already handle these.
